### ISSUE TITLE
Ends with "a" changed to "um"

### ISSUE THREAD

**Issue by GunTotnHippie** [codesmithtools/SchemaHelper#3]
I can't seem to find this problem but somewhere in SchemaHelper (I believe) the table name is changing my StockMeta table to StockMetum table.  Also happens when I use StockData (StockDatum).  Is there a way to bypass this check and worst case can you point me to where this is happening so I can fix a rebuild?

Thanks,
Brian

**Comment by niemyjski** [comment]
There are two ways.. there is a SchemaHelper.Configuration property that contains a bunch of naming conventions so you can set it to preserve and it will be preserved. I also, think you can set an extended property on it called cs_name with your value. Can you try this.

**Comment by GunTotnHippie** [comment]
Perfect, great help as usual!  
Answer: CodeSmith.SchemaHelper.Configuration.Instance.NamingProperty.EntityNaming = EntityNaming.Preserve;
